### ISSUE TITLE
method_missing error when calling username from Bowline::AppConfig

### ISSUE THREAD

**Issue by postmodern** [maccman/bowline-twitter#3]
After running `bundle install` and `bundle exec ./script/run` I got this method_missing exception from Bowline::AppConfig on Ruby 1.9.2-preview3:

```
$ bundle exec ./script/run 
Setting up Bowline. This could take a while...
/home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/activemodel-3.0.0.beta4/lib/active_model/attribute_methods.rb:358:in `method_missing': undefined method `username' for #<Bowline::AppConfig:0xa4477f8> (NoMethodError)
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/supermodel-0.1.3/lib/supermodel/base.rb:282:in `method_missing'
from /home/hal/bowline-twitter/app/models/tweet.rb:28:in `twitter'
from /home/hal/bowline-twitter/app/models/tweet.rb:19:in `timeline'
from /home/hal/bowline-twitter/app/models/tweet.rb:7:in `poll'
from /home/hal/bowline-twitter/config/initializers/tweet.rb:1:in `<top (required)>'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:208:in `load'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:208:in `block in load'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:200:in `load_dependency'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:208:in `load'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/bowline-0.9.3/lib/bowline/initializer.rb:238:in `block in load_application_initializers'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/bowline-0.9.3/lib/bowline/initializer.rb:237:in `each'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/bowline-0.9.3/lib/bowline/initializer.rb:237:in `load_application_initializers'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/bowline-0.9.3/lib/bowline/initializer.rb:364:in `process'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/bowline-0.9.3/lib/bowline/initializer.rb:71:in `run'
from /home/hal/bowline-twitter/config/environment.rb:4:in `<top (required)>'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `block in require'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `block in load_dependency'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:554:in `new_constants_in'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `load_dependency'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/bowline-0.9.3/lib/bowline/tasks/misc.rake:2:in `block in <top (required)>'
from /home/hal/.rvm/rubies/ruby-1.9.2-preview3/lib/ruby/1.9.1/rake.rb:634:in `call'
from /home/hal/.rvm/rubies/ruby-1.9.2-preview3/lib/ruby/1.9.1/rake.rb:634:in `block in execute'
from /home/hal/.rvm/rubies/ruby-1.9.2-preview3/lib/ruby/1.9.1/rake.rb:629:in `each'
from /home/hal/.rvm/rubies/ruby-1.9.2-preview3/lib/ruby/1.9.1/rake.rb:629:in `execute'
from /home/hal/.rvm/rubies/ruby-1.9.2-preview3/lib/ruby/1.9.1/rake.rb:595:in `block in invoke_with_call_chain'
from /home/hal/.rvm/rubies/ruby-1.9.2-preview3/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
from /home/hal/.rvm/rubies/ruby-1.9.2-preview3/lib/ruby/1.9.1/rake.rb:588:in `invoke_with_call_chain'
from /home/hal/.rvm/rubies/ruby-1.9.2-preview3/lib/ruby/1.9.1/rake.rb:605:in `block in invoke_prerequisites'
from /home/hal/.rvm/rubies/ruby-1.9.2-preview3/lib/ruby/1.9.1/rake.rb:602:in `each'
from /home/hal/.rvm/rubies/ruby-1.9.2-preview3/lib/ruby/1.9.1/rake.rb:602:in `invoke_prerequisites'
from /home/hal/.rvm/rubies/ruby-1.9.2-preview3/lib/ruby/1.9.1/rake.rb:594:in `block in invoke_with_call_chain'
from /home/hal/.rvm/rubies/ruby-1.9.2-preview3/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
from /home/hal/.rvm/rubies/ruby-1.9.2-preview3/lib/ruby/1.9.1/rake.rb:588:in `invoke_with_call_chain'
from /home/hal/.rvm/rubies/ruby-1.9.2-preview3/lib/ruby/1.9.1/rake.rb:581:in `invoke'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/bowline-0.9.3/lib/bowline/commands/run.rb:4:in `<top (required)>'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `block in require'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `block in load_dependency'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:554:in `new_constants_in'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `load_dependency'
from /home/hal/.rvm/gems/ruby-1.9.2-preview3/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
from ./script/run:3:in `<main>'
```

**Comment by maccman** [comment]
That would probably be because you haven't copied over config/application.example.yml to config/application.yml
