### ISSUE TITLE
Bind method not found

### ISSUE THREAD

**Issue by ghost** [maccman/bowline-twitter#4]
Hi,

I'm trying to learn the basic twitter app using bowline. Im running on an Ubuntu 9.04
and have installed Ruby 1.9. Everything in the installation worked as described, even tho I had to add: require "twitter" to app/models/tweet.rb

Then when I try to run the app, this is what I get:

[13:19][vadmin@vadmin:~/Documents/bowline_twitter]$ script/run

<code>
/home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/environment.rb:6: warning: Insecure world writable dir /home/vadmin/Documents in PATH, mode 040777
Setting up Bowline. This could take a while...
/home/vadmin/Documents/bowline_twitter/app/binders/tweets_binder.rb:5: undefined method `bind' for TweetsBinder:Class (NoMethodError)
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in`require'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:200:in `load_dependency'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in`require'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:319:in `require_or_load'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:273:in`depend_on'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:189:in `require_dependency'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/initializer.rb:269:in`load_application_classes'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/initializer.rb:268:in `each'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/initializer.rb:268:in`load_application_classes'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/initializer.rb:266:in `each'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/initializer.rb:266:in`load_application_classes'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/initializer.rb:355:in `process'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/initializer.rb:71:in`send'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/initializer.rb:71:in `run'
    from /home/vadmin/Documents/bowline_twitter/config/environment.rb:4
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in`require'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `load_dependency'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:554:in`new_constants_in'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in `load_dependency'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in`require'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/tasks/misc.rake:2
    from /usr/lib/ruby/1.8/rake.rb:546:in `call'
    from /usr/lib/ruby/1.8/rake.rb:546:in`execute'
    from /usr/lib/ruby/1.8/rake.rb:541:in `each'
    from /usr/lib/ruby/1.8/rake.rb:541:in`execute'
    from /usr/lib/ruby/1.8/rake.rb:508:in `invoke_with_call_chain'
    from /usr/lib/ruby/1.8/rake.rb:501:in`synchronize'
    from /usr/lib/ruby/1.8/rake.rb:501:in `invoke_with_call_chain'
    from /usr/lib/ruby/1.8/rake.rb:518:in`invoke_prerequisites'
    from /usr/lib/ruby/1.8/rake.rb:1183:in `each'
    from /usr/lib/ruby/1.8/rake.rb:1183:in`send'
    from /usr/lib/ruby/1.8/rake.rb:1183:in `each'
    from /usr/lib/ruby/1.8/rake.rb:515:in`invoke_prerequisites'
    from /usr/lib/ruby/1.8/rake.rb:507:in `invoke_with_call_chain'
    from /usr/lib/ruby/1.8/rake.rb:501:in`synchronize'
    from /usr/lib/ruby/1.8/rake.rb:501:in `invoke_with_call_chain'
    from /usr/lib/ruby/1.8/rake.rb:494:in`invoke'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/commands/run.rb:4
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in`load_dependency'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:554:in `new_constants_in'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:198:in`load_dependency'
    from /home/vadmin/Documents/bowline_twitter/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
    from script/run:3
</code>

**Comment by maccman** [comment]
Hmm, not sure what's happening here. I have the same env, seems to work for me. Sorry I can't be more help.
