### ISSUE TITLE
Can't run this app

### ISSUE THREAD

**Issue by semaperepelitsa** [maccman/bowline-twitter#6]
I cloned this git repository, executed `bundle install` and then tried to run this app:

```
% script/run
Setting up Bowline. This could take a while...
/Users/sema/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:2482:in `const_missing': uninitialized constant Twitter::HTTPAuth (NameError)
    from /Users/sema/Code/bowline-twitter/app/models/tweet.rb:27:in `twitter'
    from /Users/sema/Code/bowline-twitter/app/models/tweet.rb:19:in `timeline'
    from /Users/sema/Code/bowline-twitter/app/models/tweet.rb:7:in `poll'
    from /Users/sema/Code/bowline-twitter/config/initializers/tweet.rb:1:in `<top (required)>'
    from /Users/sema/.rvm/gems/ruby-1.9.2-p0/gems/bowline-0.9.4/lib/bowline/initializer.rb:233:in `block in load_application_initializers'
    from /Users/sema/.rvm/gems/ruby-1.9.2-p0/gems/bowline-0.9.4/lib/bowline/initializer.rb:232:in `each'
    from /Users/sema/.rvm/gems/ruby-1.9.2-p0/gems/bowline-0.9.4/lib/bowline/initializer.rb:232:in `load_application_initializers'
    from /Users/sema/.rvm/gems/ruby-1.9.2-p0/gems/bowline-0.9.4/lib/bowline/initializer.rb:359:in `process'
    from /Users/sema/.rvm/gems/ruby-1.9.2-p0/gems/bowline-0.9.4/lib/bowline/initializer.rb:71:in `run'
    from /Users/sema/Code/bowline-twitter/config/environment.rb:4:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /Users/sema/.rvm/gems/ruby-1.9.2-p0/gems/bowline-0.9.4/lib/bowline/tasks/misc.rake:2:in `block in <top (required)>'
    from /Users/sema/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:634:in `call'
    from /Users/sema/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:634:in `block in execute'
    from /Users/sema/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:629:in `each'
    from /Users/sema/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:629:in `execute'
    from /Users/sema/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:595:in `block in invoke_with_call_chain'
    from /Users/sema/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
    from /Users/sema/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:588:in `invoke_with_call_chain'
    from /Users/sema/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:605:in `block in invoke_prerequisites'
    from /Users/sema/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:602:in `each'
    from /Users/sema/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:602:in `invoke_prerequisites'
    from /Users/sema/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:594:in `block in invoke_with_call_chain'
    from /Users/sema/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
    from /Users/sema/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:588:in `invoke_with_call_chain'
    from /Users/sema/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:581:in `invoke'
    from /Users/sema/.rvm/gems/ruby-1.9.2-p0/gems/bowline-0.9.4/lib/bowline/commands/run.rb:4:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from script/run:3:in `<main>'
```

**Comment by baldrailers** [comment]
Twitter's HTTP Basic Authentication was discontinued. I forked this project and added the OAuth version. I'll push the working codes within this week.

Cheers!

**Comment by gabrielmancini** [comment]
same error
