### ISSUE TITLE
Method missing using RVM

### ISSUE THREAD

**Issue by rodrigotoledo** [maccman/bowline-twitter#9]
Hi,
im using RVM in MacOSx and had this problem when i try install with bundler:

bowline-bundle install
/Users/rtoledo/.rvm/gems/ruby-1.9.2-p136@bowline/gems/bowline-bundler-0.0.4/lib/bowline/bundler/dependency.rb:59:in `<class:Dependency>': undefined method`version_requirements' for class `Bundler::Dependency' (NameError)
    from /Users/rtoledo/.rvm/gems/ruby-1.9.2-p136@bowline/gems/bowline-bundler-0.0.4/lib/bowline/bundler/dependency.rb:4:in`module:Bundler'
    from /Users/rtoledo/.rvm/gems/ruby-1.9.2-p136@bowline/gems/bowline-bundler-0.0.4/lib/bowline/bundler/dependency.rb:1:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from internal:lib/rubygems/custom_require:29:in `require'
    from /Users/rtoledo/.rvm/gems/ruby-1.9.2-p136@bowline/gems/bowline-bundler-0.0.4/lib/bowline/bundler.rb:18:in`<top (required)>'
    from internal:lib/rubygems/custom_require:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from /Users/rtoledo/.rvm/gems/ruby-1.9.2-p136@bowline/gems/bowline-bundler-0.0.4/bin/bowline-bundle:4:in `<top (required)>'
    from /Users/rtoledo/.rvm/gems/ruby-1.9.2-p136@bowline/bin/bowline-bundle:19:in`load'
    from /Users/rtoledo/.rvm/gems/ruby-1.9.2-p136@bowline/bin/bowline-bundle:19:in `<main>'

em list

**\* LOCAL GEMS ***

activemodel (3.0.7.rc2)
activesupport (3.0.7.rc2)
bowline (0.9.4)
bowline-bundler (0.0.4)
builder (2.1.2)
bundler (1.0.12)
diff-lcs (1.1.2)
extlib (0.9.15)
highline (1.6.1)
i18n (0.5.0)
rake (0.8.7)
rubygems-update (1.7.2)
rubyzip2 (2.0.1)
supermodel (0.1.4)
templater (1.0.0)

**Comment by citelao** [comment]
Ditto.

**Comment by amiel** [comment]
Same here
